import { RotateCcw, Save, Settings2 } from "lucide-react";
import { PageHeader } from "../../components/ui/PageHeader";
import { useAppData } from "../../contexts/AppDataContext";
import { useNotifications } from "../../contexts/NotificationContext";
import { usePreferences } from "../../contexts/PreferencesContext";

export default function SettingsPage() {
  const { preferences, updatePreferences, resetPreferences } = usePreferences();
  const { dispatch } = useAppData();
  const { showNotification } = useNotifications();
  const save = (event) => { event.preventDefault(); showNotification({ type: "success", message: "Settings saved to localStorage." }); };
  return <div className="page-stack"><PageHeader eyebrow="Lazy-loaded module" title="Settings" description="Preferences persist safely through the reusable useLocalStorage hook." /><form className="settings-layout" onSubmit={save}><section className="panel settings-panel"><div className="settings-heading"><span><Settings2 size={21} /></span><div><h2>Workspace preferences</h2><p>Choose how data is displayed on this device.</p></div></div><div className="settings-fields"><label><span>Theme</span><select value={preferences.theme} onChange={(event) => updatePreferences({ theme: event.target.value })}><option value="light">Light</option><option value="dark">Dark</option></select></label><label><span>Currency</span><select value={preferences.currency} onChange={(event) => updatePreferences({ currency: event.target.value })}><option>USD</option><option>EUR</option><option>GBP</option></select></label><label><span>Low-stock threshold</span><input type="number" min="0" value={preferences.lowStockThreshold} onChange={(event) => updatePreferences({ lowStockThreshold: Number(event.target.value) })} /></label><label className="toggle-row"><span><strong>Compact tables</strong><small>Reduce vertical spacing in administrative tables.</small></span><input type="checkbox" checked={preferences.compactTables} onChange={(event) => updatePreferences({ compactTables: event.target.checked })} /></label><label className="toggle-row"><span><strong>Email summaries</strong><small>Demo preference only; no messages are sent.</small></span><input type="checkbox" checked={preferences.emailSummaries} onChange={(event) => updatePreferences({ emailSummaries: event.target.checked })} /></label></div><div className="form-actions"><button className="button button-ghost" type="button" onClick={() => { resetPreferences(); showNotification({ type: "info", message: "Preferences reset." }); }}><RotateCcw size={16} /> Reset</button><button className="button button-primary" type="submit"><Save size={16} /> Save settings</button></div></section><aside className="panel settings-danger"><p className="eyebrow">Demo controls</p><h2>Reset application data</h2><p>Restore products, orders, customers, and cart data to the original seed records.</p><button className="button button-danger" type="button" onClick={() => { dispatch({ type: "RESET_DATA" }); showNotification({ type: "warning", message: "Demo data restored." }); }}>Reset demo data</button></aside></form></div>;
}
